### ISSUE TITLE
"SW?" "D?"

### ISSUE THREAD

**Issue by haywirephoenix** [arjhun/KiCad-helper-scripts#2]
Switch and Diode ID labels don't seem to generate. Is this what  eeschema.createId() is supposed to do? They are shown this way in the readme image aswell.

**Comment by arjhun** [comment]
Hello @haywirephoenix ,

The labels are created in Eeschema by hand, I don't want to mess up existing symbol labels with this script, commonly you use the 'annotate schematic symbols' for this.

see step 45 in: https://docs.kicad-pcb.org/5.1.5/en/getting_started_in_kicad/getting_started_in_kicad.html#draw-electronic-schematics

It auto names and numbers symbols for you, so you don't accidentally have two of the same annotations. The `createId()` function is just an id under the hood and Eeschema uses it to keep track of the components.  This is separate from the name you give it!

Good luck!
