### ISSUE TITLE
Symbols appear as "??"

### ISSUE THREAD

**Issue by radishdalek** [arjhun/KiCad-helper-scripts#3]
When opening the schematic, KICAD opens the Remap symbols dialogue as it cannot connect the generated matrix to the symbols. 
- If I tell it to remap symbols, all symbols are "??"
- If I tell it to close the dialogue without remapping, all the symbols are still "??"

![symbol problems](https://user-images.githubusercontent.com/16018920/74608501-7cca9d00-50d9-11ea-9c5e-d4b40a3431c3.png)

To fix, I have to edit each symbol properties and reassign symbol. 

KICAD version: (5.1.5)-3 release build
Script version used: release of Dec 2019
Python interpreter: WinPython 3.8 (https://winpython.github.io/) - IDLE (Python GUI).exe

**Comment by arjhun** [comment]
I think i fixed it... please clone or download again

**Comment by kimsr96** [comment]
I have same problem too
MAC OS

**Comment by arjhun** [comment]
Closing
